_target_: model.network.vision.HoMVision
nb_classes: ${data.num_classes}
dim: 256
im_size: 256
kernel_size: 32
nb_layers: 4
order: 2
order_expand: 4
ffw_expand: 4
dropout: 0.0
pooling: cls
in_conv: true
